Blocked Windows Logins by Host:
  resource_name:
    projects/1234567891234/locations/us/instances/3f0ac524-5ae1-4bfd-b86d-53afc953e7e6/users/me/searchQueries/74257fc4-cb92-497d-84be-c9b5bfcd287c
  query_id: Ab9e5XWvQTu46prKxvQx6Q==
  user_id: player1@example.com
  create_time: '2025-11-07T16:17:40.197090Z'
  update_time: '2025-11-07T16:17:40.197090Z'
  description: Statistical Search Workshop
  query: |-
    metadata.vendor_name = "Microsoft" AND metadata.product_name = /Windows/ AND metadata.event_type = "USER_LOGIN" AND security_result.action = "BLOCK" AND principal.hostname != ""
    $host = principal.hostname
    $user = target.user.userid
    match:
      $host
    outcome:
      $user_distinct_count = count_distinct($user)
      $user_count = count($user)
      $users_uniq_list = array_distinct($user)
    order:
       $user_count desc, $user_distinct_count desc
  sharing_mode:
  query_type:
  placeholder_names:
  placeholder_descriptions:
Blocked Windows Logins by Host:
  resource_name:
    projects/1234567891234/locations/us/instances/3f0ac524-5ae1-4bfd-b86d-53afc953e7e6/users/me/searchQueries/74257fc4-cb92-497d-84be-c9b5bfcd287c
  query_id: Ab9e5XWvQTu46prKxvQx6Q==
  user_id: player1@example.com
  create_time: '2025-11-07T16:17:40.197090Z'
  update_time: '2025-11-07T16:17:40.197090Z'
  description: Statistical Search Workshop
  query: |-
    metadata.vendor_name = "Microsoft" AND metadata.product_name = /Windows/ AND metadata.event_type = "USER_LOGIN" AND security_result.action = "BLOCK" AND principal.hostname != ""
    $host = principal.hostname
    $user = target.user.userid
    match:
      $host
    outcome:
      $user_distinct_count = count_distinct($user)
      $user_count = count($user)
      $users_uniq_list = array_distinct($user)
    order:
       $user_count desc, $user_distinct_count desc
  sharing_mode:
  query_type:
  placeholder_names:
  placeholder_descriptions:
